"""5-max no-limit Texas Hold'em engine and training primitives."""

from .betting import Action, PlayerState, Pot
from .bots import AggroBot, BotStatistics, CallingStationBot, PokerBot, RandomBot, RuleBot, TightBot
from .cards import Card, Deck
from .environment import HoldemEnvironment
from .equity import (
    EquityCalibrationBin,
    EquityMetrics,
    EquitySnapshot,
    EquityTarget,
    capture_equity_snapshot,
    equity_cross_entropy,
    equity_metrics,
    generate_equity_target,
)
from .game_state import HandState, Street
from .observation import OBSERVATION_VERSION, Observation, ObservationFeatureStatistics, observation_for
from .simulator import BatchedHoldemEnvironment, BatchStep, SimulationBenchmark, benchmark_hands
from .tournament import TournamentResult, run_tournament
from .model import (
    ACTION_NAMES,
    BET_SIZE_ACTIONS,
    EQUITY_OUTCOMES,
    MODEL_VERSION,
    TORCH_AVAILABLE,
    InferenceDecision,
    ModelConfig,
    ModelOutput,
    PokerAgentModel,
)
from .curriculum import (
    CheckpointTransfer,
    CurriculumConfig,
    CurriculumStage,
    CurriculumStageSpec,
    PretrainingExample,
    RegressionCase,
    RegressionControlSet,
    RegressionResult,
    STAGE_SPECS,
    StageEvaluation,
    StageScheduler,
    StageTransitionError,
    TracePretrainingDataset,
    checkpoint_curriculum_metadata,
    generate_pretraining_dataset,
    save_curriculum_checkpoint,
    stage_spec,
    transfer_checkpoint,
)

__all__ = [
    "Action",
    "ACTION_NAMES",
    "AggroBot",
    "BatchedHoldemEnvironment",
    "BatchStep",
    "Card",
    "CheckpointTransfer",
    "CurriculumConfig",
    "CurriculumStage",
    "CurriculumStageSpec",
    "BotStatistics",
    "BET_SIZE_ACTIONS",
    "CallingStationBot",
    "Deck",
    "EQUITY_OUTCOMES",
    "EquityCalibrationBin",
    "EquityMetrics",
    "EquitySnapshot",
    "EquityTarget",
    "HandState",
    "HoldemEnvironment",
    "OBSERVATION_VERSION",
    "MODEL_VERSION",
    "Observation",
    "ObservationFeatureStatistics",
    "InferenceDecision",
    "ModelConfig",
    "ModelOutput",
    "PlayerState",
    "Pot",
    "PokerBot",
    "PokerAgentModel",
    "PretrainingExample",
    "RandomBot",
    "RegressionCase",
    "RegressionControlSet",
    "RegressionResult",
    "RuleBot",
    "SimulationBenchmark",
    "Street",
    "STAGE_SPECS",
    "StageEvaluation",
    "StageScheduler",
    "StageTransitionError",
    "TORCH_AVAILABLE",
    "TightBot",
    "TournamentResult",
    "TracePretrainingDataset",
    "benchmark_hands",
    "checkpoint_curriculum_metadata",
    "capture_equity_snapshot",
    "equity_cross_entropy",
    "equity_metrics",
    "generate_equity_target",
    "generate_pretraining_dataset",
    "run_tournament",
    "observation_for",
    "save_curriculum_checkpoint",
    "stage_spec",
    "transfer_checkpoint",
]
