"""5-max no-limit Texas Hold'em engine and training primitives."""

from .betting import Action, PlayerState, Pot
from .bots import AggroBot, BotStatistics, CallingStationBot, PokerBot, RandomBot, RuleBot, TightBot
from .cards import Card, Deck
from .environment import HoldemEnvironment
from .equity import (
    EquityCalibrationBin,
    EquityMetrics,
    EquitySnapshot,
    EquityTarget,
    ExpectedShowdownShareMetrics,
    capture_equity_snapshot,
    equity_cross_entropy,
    equity_metrics,
    expected_showdown_share_binary_cross_entropy,
    expected_showdown_share_metrics,
    generate_equity_target,
)
from .game_state import HandState, Street
from .observation import OBSERVATION_VERSION, Observation, ObservationFeatureStatistics, observation_for
from .simulator import BatchedHoldemEnvironment, BatchStep, SimulationBenchmark, benchmark_hands
from .tournament import TournamentResult, run_tournament
from .evaluation import (
    EvaluationConfig,
    EvaluationSuiteReport,
    MatchupReport,
    ModelDiagnostics,
    PokerStyleStatistics,
    SanityScenarioResult,
    evaluate_suite,
    run_sanity_checks,
)
from .model import (
    ACTION_NAMES,
    BET_SIZE_ACTIONS,
    EQUITY_OUTCOMES,
    MODEL_VERSION,
    TORCH_AVAILABLE,
    InferenceDecision,
    ModelConfig,
    ModelOutput,
    PokerAgentModel,
)
from .inference import CheckpointInferenceService, HeuristicInferenceService, InferenceResponse, ScalarMetric
from .model_migration import MIGRATION_VERSION, V2_MODEL_VERSION, migrate_v2_checkpoint
from .game_server import GameServer, ObservableHand
from .curriculum import (
    CheckpointTransfer,
    CurriculumConfig,
    CurriculumStage,
    CurriculumStageSpec,
    PretrainingExample,
    RegressionCase,
    RegressionControlSet,
    RegressionResult,
    STAGE_SPECS,
    StageEvaluation,
    StageScheduler,
    StageTransitionError,
    TracePretrainingDataset,
    checkpoint_curriculum_metadata,
    generate_pretraining_dataset,
    save_curriculum_checkpoint,
    stage_spec,
    transfer_checkpoint,
)
from .pretraining import EquityBackbonePretrainer, PretrainingConfig, PretrainingMetrics, PretrainingValidation
from .pretraining_data import PretrainingCorpus, SeedRange, generate_pretraining_corpus, load_pretraining_corpus, write_pretraining_corpus
from .pretraining_runner import AcceptanceConfig, CorpusConfig, PretrainingRunConfig, PretrainingRunResult, PretrainingRunner
from .promotion import PromotionConfig, PromotionEvaluation, PromotionEvaluator
from .curriculum_transition import (
    CurriculumTransitionConfig,
    CurriculumTransitionEvaluator,
    TransitionEvaluation,
    TransitionEvidence,
)
from .multiway_evaluation import (
    MultiwayEvaluationConfig,
    MultiwayEvaluationReport,
    OpponentSeat,
    PairedMultiwayEvaluation,
    evaluate_multiway_suite,
    pair_multiway_reports,
)
from .paired_rung import PairedRungConfig, PairedRungResult, PairedRungRunner
from .curriculum_coordinator import (
    CurriculumCoordinator,
    CurriculumCoordinatorConfig,
    CurriculumTransitionDecision,
    EvaluationProtocol,
    OpponentSpec,
    native_paired_rung_runner,
)
from .curriculum_runtime import CurriculumJobConfig, native_multiway_evaluator
from .experiments import ExperimentConfig, ExperimentEvent, ExperimentLedger
from .experiment_runner import ExperimentRunResult, ExperimentRunner
from .tuning import (
    MaterializedTrial,
    SweepConfig,
    TrialSpec,
    TuningComparisonReport,
    TuningEvidence,
    compare_tuning_evidence,
    hu_promotion_protocol_payload,
    materialize_sweep,
    publish_tuning_evaluation,
    write_hu_promotion_protocol,
)
from .releases import LineageArtifact, ReleaseRecord, ReleaseRegistry, ReleaseRequest

__all__ = [
    "Action",
    "ACTION_NAMES",
    "AggroBot",
    "BatchedHoldemEnvironment",
    "BatchStep",
    "Card",
    "CheckpointInferenceService",
    "CheckpointTransfer",
    "CurriculumConfig",
    "CurriculumStage",
    "CurriculumStageSpec",
    "CurriculumTransitionConfig",
    "CurriculumTransitionEvaluator",
    "BotStatistics",
    "BET_SIZE_ACTIONS",
    "CallingStationBot",
    "Deck",
    "EQUITY_OUTCOMES",
    "EvaluationConfig",
    "EvaluationSuiteReport",
    "ExperimentConfig",
    "ExperimentEvent",
    "ExperimentLedger",
    "ExperimentRunResult",
    "ExperimentRunner",
    "EquityCalibrationBin",
    "EquityBackbonePretrainer",
    "EquityMetrics",
    "EquitySnapshot",
    "EquityTarget",
    "ExpectedShowdownShareMetrics",
    "HandState",
    "GameServer",
    "HeuristicInferenceService",
    "HoldemEnvironment",
    "OBSERVATION_VERSION",
    "MODEL_VERSION",
    "Observation",
    "ObservationFeatureStatistics",
    "ObservableHand",
    "InferenceDecision",
    "InferenceResponse",
    "ScalarMetric",
    "MIGRATION_VERSION",
    "V2_MODEL_VERSION",
    "ModelConfig",
    "ModelDiagnostics",
    "ModelOutput",
    "MatchupReport",
    "MaterializedTrial",
    "LineageArtifact",
    "PlayerState",
    "Pot",
    "PokerBot",
    "PokerStyleStatistics",
    "PokerAgentModel",
    "PretrainingExample",
    "PretrainingConfig",
    "PretrainingCorpus",
    "PretrainingMetrics",
    "PretrainingRunConfig",
    "PretrainingRunResult",
    "PretrainingRunner",
    "PretrainingValidation",
    "PromotionConfig",
    "PromotionEvaluation",
    "PromotionEvaluator",
    "RandomBot",
    "RegressionCase",
    "RegressionControlSet",
    "RegressionResult",
    "ReleaseRecord",
    "ReleaseRegistry",
    "ReleaseRequest",
    "RuleBot",
    "SimulationBenchmark",
    "SanityScenarioResult",
    "Street",
    "STAGE_SPECS",
    "StageEvaluation",
    "StageScheduler",
    "StageTransitionError",
    "SweepConfig",
    "AcceptanceConfig",
    "CorpusConfig",
    "SeedRange",
    "TORCH_AVAILABLE",
    "TightBot",
    "TransitionEvaluation",
    "TransitionEvidence",
    "TournamentResult",
    "TrialSpec",
    "TuningComparisonReport",
    "TuningEvidence",
    "TracePretrainingDataset",
    "benchmark_hands",
    "checkpoint_curriculum_metadata",
    "capture_equity_snapshot",
    "equity_cross_entropy",
    "equity_metrics",
    "expected_showdown_share_binary_cross_entropy",
    "expected_showdown_share_metrics",
    "evaluate_suite",
    "generate_equity_target",
    "generate_pretraining_dataset",
    "generate_pretraining_corpus",
    "load_pretraining_corpus",
    "migrate_v2_checkpoint",
    "run_tournament",
    "run_sanity_checks",
    "observation_for",
    "save_curriculum_checkpoint",
    "stage_spec",
    "transfer_checkpoint",
    "write_pretraining_corpus",
    "CurriculumCoordinator",
    "CurriculumCoordinatorConfig",
    "CurriculumJobConfig",
    "CurriculumTransitionDecision",
    "EvaluationProtocol",
    "MultiwayEvaluationConfig",
    "MultiwayEvaluationReport",
    "OpponentSeat",
    "OpponentSpec",
    "PairedMultiwayEvaluation",
    "PairedRungConfig",
    "PairedRungResult",
    "PairedRungRunner",
    "evaluate_multiway_suite",
    "native_multiway_evaluator",
    "native_paired_rung_runner",
    "pair_multiway_reports",
    "compare_tuning_evidence",
    "hu_promotion_protocol_payload",
    "materialize_sweep",
    "publish_tuning_evaluation",
    "write_hu_promotion_protocol",
]
